### ISSUE TITLE
Event ID Sort not working

### ISSUE THREAD

**Issue by JohnBrooking** [bicycle-coalition-of-maine/BPSETracker#12]
Doesn't change anything.

**Comment by SpruceWillows** [comment]
Ditto for the Assign Instructor page, sorting does not work for "new request only" though it appears to work correctly for "all requests".

**Comment by JohnBrooking** [comment]
Changes for To Do #16 ("Add BCM Staff events to data") also fixed the EventID sort issue on the Event summary page. The Assign Instructor page also now works to sort by RequestDate, although it does not offer the Event ID column or other filtering like the Event summary page does.
