### ISSUE TITLE
"Report on Activity" not working

### ISSUE THREAD

**Issue by SpruceWillows** [bicycle-coalition-of-maine/BPSETracker#17]
https://bpse.bikemaine.org/index.php?r=event%2F%23 
Page not working, results in not found 404.

**Comment by JohnBrooking** [comment]
Correct. That will be the entry into the reporting system, to be developed over the winter. I should have put a "Coming Soon" placeholder page into there for now, but that just didn't rise up to the top of the priority list so far. Maybe I'll do that if I think of it sometime when I'm doing something else.

**Comment by JohnBrooking** [comment]
Put in a "Coming Soon" placeholder page for now. The report system is planned for v1.2.5 in March.
