### ISSUE TITLE
Allow display name in email address configuration

### ISSUE THREAD

**Issue by JohnBrooking** [bicycle-coalition-of-maine/BPSETracker#22]
In the Configuration screen, where email addresses are defined, you can currently only list the email address(es). Would be nice to allow a display name as well, such as "Erik daSilva <erik@bikemaine.org>". That would allow the real name to be displayed in email message headers.

**Comment by SpruceWillows** [comment]
This would absolutely be helpful.

**Comment by JohnBrooking** [comment]
Now working. Syntax is i.e.

> Erik da Silva \<erik@bikemaine.org\>
