### ISSUE TITLE
Allow CC recipients in email configuration

### ISSUE THREAD

**Issue by JohnBrooking** [bicycle-coalition-of-maine/BPSETracker#23]
In the configuration screen email recipients lists, you can specify multiple people by separating the addresses with commas or semi-colons. I had intended to allow a "CC:" prefix to be used for any address, to specify copying them instead of list them as a regular recipient, but I just haven't gotten around to it yet.

**Comment by SpruceWillows** [comment]
CC would be helpful, but isn't going to slow my work. This could be the last item you work on and it would be OK :)

**Comment by JohnBrooking** [comment]
Now working. Prefix with CC:, i.e.

> Erik da Silva \<erik@bikemaine.org\>, CC:John Brooking \<johnbrooking4@gmail.com\>
