### ISSUE TITLE
Instructor name links to event host

### ISSUE THREAD

**Issue by SpruceWillows** [bicycle-coalition-of-maine/BPSETracker#34]
I just clicked on Julie's name on the below screenshot
![Screen Shot 2020-08-18 at 4 22 56 PM](https://user-images.githubusercontent.com/50148350/90561708-1baa8180-e16f-11ea-8b50-84c1be182f53.png)
And instead of seeing the instructor info I saw the event host's name (below screenshot) for the event Julie provided education at.
![Screen Shot 2020-08-18 at 4 22 59 PM](https://user-images.githubusercontent.com/50148350/90561806-3f6dc780-e16f-11ea-9bbf-36c1a8acbe98.png)

I assume I should have seen Julie's info, not Lisa's.

**Comment by JohnBrooking** [comment]
Yep, looks like a bug. I probably just have the wrong field name somewhere. Hopefully an easy fix, maybe tonight.

**Comment by JohnBrooking** [comment]
Fixed!
